// modulosData.js
// Contenido de cada módulo del menú "Productos".
// Los textos son de relleno (placeholder) redactados en el mismo tono
// que la captura original; reemplázalos por el copy real del cliente.

const modulosData = {
  contabilidad: {
    menuLabel: "Módulo De Contabilidad",
    titulo: "MÓDULO DE CONTABILIDAD",
    fecha: "20 Jul, 2015",
    autor: "Juan Pérez",
    vistas: "12,708",
    intro: [
      "El Módulo de Contabilidad permite llevar el control completo de la operación contable de su empresa, desde el registro de asientos hasta la generación automática de los estados financieros, cumpliendo con la normativa vigente.",
      "Su diseño intuitivo permite que tanto contadores como auxiliares administrativos trabajen sobre la misma base de datos en tiempo real, reduciendo errores de digitación y tiempos de cierre mensual.",
    ],
    features: [
      "Módulos empresariales integrados",
      "Bancos y conciliación bancaria",
      "Ajustes contables automáticos",
      "Generación de plan de cuentas configurable",
      "Ver e imprimir plan de cuentas",
      "Ver e imprimir libro mayor con auxiliar por proyecto o cuenta",
      "Registro de libros de compras y ventas por vendedor o sucursal",
      "Digitación múltiple de facturas de compras y ventas",
      "Exportar libro de compras y ventas",
      "Generación de cuadros de saldos automáticos a partir del libro de ventas",
      "Balance de sumas y saldos, estado de resultados por período y consolidado",
      "Catálogo de análisis de ingresos y egresos",
      "Listado de proyectos",
      "Libros informativos",
      "Consolidación de empresas",
      "Listado de clientes",
      "Manejo de exoneraciones y retenciones de impuestos",
    ],
    videoTitulo: "VIDEO DE PRESENTACIÓN — MÓDULO DE CONTABILIDAD",
  },

  inventario: {
    menuLabel: "Módulo De Inventario",
    titulo: "MÓDULO DE INVENTARIO",
    fecha: "3 Ago, 2015",
    autor: "Juan Pérez",
    vistas: "9,214",
    intro: [
      "El Módulo de Inventario le permite controlar existencias, movimientos de bodega y costos de cada artículo en tiempo real, integrándose directamente con los módulos de Contabilidad y Facturación.",
      "Incluye alertas de stock mínimo, trazabilidad por lote y reportes de rotación que facilitan la toma de decisiones de compra y reposición.",
    ],
    features: [
      "Control de existencias en múltiples bodegas",
      "Kardex valorado por método PEPS o promedio",
      "Alertas de stock mínimo y máximo",
      "Traslados entre bodegas con trazabilidad",
      "Toma física de inventario con lector de códigos",
      "Costeo automático por artículo",
      "Listado de artículos por categoría y proveedor",
      "Reporte de rotación e inventario obsoleto",
      "Manejo de lotes y fechas de vencimiento",
      "Integración directa con facturación y compras",
      "Ajustes de inventario con justificación",
      "Exportación de listados a Excel y PDF",
      "Historial de movimientos por artículo",
      "Catálogo de unidades de medida configurable",
      "Consolidación de inventario por sucursal",
    ],
    videoTitulo: "VIDEO DE PRESENTACIÓN — MÓDULO DE INVENTARIO",
  },

  planilla: {
    menuLabel: "Módulo De Planilla De Sueldos",
    titulo: "MÓDULO DE PLANILLA DE SUELDOS",
    fecha: "14 Sep, 2015",
    autor: "Juan Pérez",
    vistas: "7,532",
    intro: [
      "El Módulo de Planilla de Sueldos automatiza el cálculo de nómina, prestaciones sociales y retenciones de ley, generando los reportes que exigen las instituciones reguladoras de forma automática.",
      "Permite manejar distintos tipos de contrato, deducciones personalizadas y la contabilización automática de la planilla en el módulo contable.",
    ],
    features: [
      "Cálculo automático de salarios y deducciones",
      "Manejo de horas extra, comisiones y bonificaciones",
      "Cálculo de vacaciones, aguinaldo y liquidaciones",
      "Reportes para seguridad social e instituto de pensiones",
      "Generación de boletas de pago individuales",
      "Contabilización automática de la planilla",
      "Manejo de múltiples tipos de contrato",
      "Control de ausentismo y permisos",
      "Historial de aumentos y movimientos salariales",
      "Reportes de costos de planilla por departamento",
      "Exportación de pagos a formato bancario",
      "Cálculo de retenciones de impuesto sobre la renta",
    ],
    videoTitulo: "VIDEO DE PRESENTACIÓN — MÓDULO DE PLANILLA DE SUELDOS",
  },

  "activos-fijos": {
    menuLabel: "Módulo De Activos Fijos",
    titulo: "MÓDULO DE ACTIVOS FIJOS",
    fecha: "2 Oct, 2015",
    autor: "Juan Pérez",
    vistas: "5,146",
    intro: [
      "El Módulo de Activos Fijos administra el ciclo de vida completo de los bienes de la empresa: adquisición, depreciación, traslados, mantenimiento y baja, con contabilización automática.",
      "Genera reportes de depreciación por método de línea recta o saldos decrecientes, facilitando la conciliación entre el área contable y el área administrativa.",
    ],
    features: [
      "Registro de activos con ficha técnica y fotografía",
      "Cálculo automático de depreciación mensual",
      "Métodos de depreciación configurables",
      "Control de ubicación y responsable del activo",
      "Traslados entre departamentos o sucursales",
      "Historial de mantenimientos realizados",
      "Baja de activos con justificación y contabilización",
      "Etiquetado con código de barras",
      "Reportes de activos totalmente depreciados",
      "Conciliación contable automática",
      "Listado de activos por categoría",
      "Exportación de reportes a Excel y PDF",
    ],
    videoTitulo: "VIDEO DE PRESENTACIÓN — MÓDULO DE ACTIVOS FIJOS",
  },

  "facturacion-nicaragua": {
    menuLabel: "Módulo De Facturación (Nicaragua)",
    titulo: "MÓDULO DE FACTURACIÓN (NICARAGUA)",
    fecha: "19 Oct, 2015",
    autor: "Juan Pérez",
    vistas: "6,890",
    intro: [
      "El Módulo de Facturación para Nicaragua cumple con los requisitos fiscales vigentes en el país, permitiendo emitir facturas, notas de crédito y débito conforme a la normativa de la Dirección General de Ingresos.",
      "Se integra con el módulo de Inventario para descargar existencias automáticamente y con Contabilidad para registrar cada venta en tiempo real.",
    ],
    features: [
      "Emisión de facturas conforme a normativa fiscal nicaragüense",
      "Notas de crédito y débito enlazadas a la factura original",
      "Manejo de impuestos IVA e ISC configurables",
      "Facturación por punto de venta y por mostrador",
      "Múltiples formas de pago en una misma factura",
      "Descarga automática de inventario al facturar",
      "Reportes de ventas por vendedor, cliente y producto",
      "Manejo de listas de precios y descuentos",
      "Cotizaciones convertibles a factura",
      "Control de facturas anuladas con motivo",
      "Reimpresión de comprobantes fiscales",
      "Cierre de caja diario por punto de venta",
    ],
    videoTitulo: "VIDEO DE PRESENTACIÓN — MÓDULO DE FACTURACIÓN (NICARAGUA)",
  },

  "facturacion-integrado": {
    menuLabel: "Módulo De Facturación (Integrado)",
    titulo: "MÓDULO DE FACTURACIÓN (INTEGRADO)",
    fecha: "5 Nov, 2015",
    autor: "Juan Pérez",
    vistas: "4,317",
    intro: [
      "El Módulo de Facturación Integrado conecta ventas, inventario, contabilidad y cuentas por cobrar en un solo flujo de trabajo, eliminando la doble digitación entre departamentos.",
      "Ideal para empresas con varias sucursales que necesitan visibilidad centralizada de la operación comercial en tiempo real.",
    ],
    features: [
      "Facturación centralizada multi-sucursal",
      "Sincronización en tiempo real entre módulos",
      "Cuentas por cobrar con antigüedad de saldos",
      "Estados de cuenta por cliente",
      "Manejo de crédito y límite por cliente",
      "Reportes consolidados de ventas por sucursal",
      "Comisiones de vendedores calculadas automáticamente",
      "Integración con el módulo de Inventario y Activos Fijos",
      "Contabilización automática de cada venta",
      "Panel de indicadores de ventas en tiempo real",
      "Control de devoluciones y notas de crédito",
      "Exportación de reportes gerenciales",
    ],
    videoTitulo: "VIDEO DE PRESENTACIÓN — MÓDULO DE FACTURACIÓN (INTEGRADO)",
  },
};

export const modulosOrden = [
  "contabilidad",
  "inventario",
  "planilla",
  "activos-fijos",
  "facturacion-nicaragua",
  "facturacion-integrado",
];

export default modulosData;
